version: "3"
services: 
  api:
    container_name: api-container
    build: .
    restart: always
    image: visual-nuts
    command: npm start
    volumes:
      - ./dist:/usr/src/visual-nuts/dist
    ports: 
      - "3001:3001"